services:
  react-app:
    build: .
    ports:
      - "5173:80" # you can also use 3000:80 or 8080:80
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
